import {expect, test} from '@playwright/test'
import {describeMobileAndDesktop} from '../tests/e2e/formFactor'
import {waitForModelReady} from '../tests/e2e/models'
import {homepageSetup, setIsReturningUser} from '../tests/e2e/utils'


/**
 * `/share/v/p/index.step` — the hosted STEP twin of the `index.ifc` logo,
 * generated by `tools/models/makeIndexStep.mjs` (see its README). It is
 * the default "open it in the viewer" target for the `/viewer/step` SEO
 * landing page, so it has to load through the STEP path and read as the
 * logo, not just parse.
 *
 * What this pins:
 *   - The file loads through Conway's AP214 path (a malformed BREP or a
 *     styling chain Conway doesn't walk still "loads" — it renders as
 *     nothing, or as default grey).
 *   - The assembly reads as the logo's sentence in the NavTree:
 *     Bldrs → Build → Every → Thing → Together ×7.
 *   - The seven blocks are seven independently selectable occurrences of
 *     two shared part shapes — the property that makes this a cheap
 *     regression asset for design/new/step-occurrence-selection.md.
 *   - It lands in the same world space as `index.ifc`, so one `#c:`
 *     camera frames both. See the second test for why that's fragile.
 */
const NAME_LEAF = 'Together'
const BLOCK_COUNT = 7
// STEP parse + BREP tessellation is slower than an IFC smoke model, and
// the first load also warms the Conway wasm.
const TEST_TIMEOUT_MS = 60_000
// Both models are ~86m across; a millimetre of float32 tessellation
// noise between the IFC and STEP paths is expected, 76m is the bug.
const ALIGNMENT_TOLERANCE_M = 0.01


/**
 * World-space bounds of everything rendered in the scene, in metres.
 * BatchedMesh/InstancedMesh need `computeBoundingBox()` on the mesh —
 * `geometry.boundingBox` is the un-instanced prototype shape, which for
 * the STEP model is one block rather than the whole logo.
 *
 * @param page the Playwright page, on a loaded model
 * @return `{min, max}` as `[x, y, z]` metre triples
 */
function sceneBounds(page: import('@playwright/test').Page) {
  return page.evaluate(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const scene = (window as any).store?.getState?.()?.viewer?.context?.getScene?.()
    if (!scene) {
      throw new Error('window.store viewer unavailable — is this a playwright-config build?')
    }
    scene.updateMatrixWorld(true)
    const min = [Infinity, Infinity, Infinity]
    const max = [-Infinity, -Infinity, -Infinity]
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    scene.traverse((o: any) => {
      if (!o.isMesh || !o.geometry) {
        return
      }
      let box
      if (o.isBatchedMesh || o.isInstancedMesh) {
        o.computeBoundingBox()
        box = o.boundingBox.clone().applyMatrix4(o.matrixWorld)
      } else {
        o.geometry.computeBoundingBox()
        box = o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld)
      }
      for (const [i, axis] of ['x', 'y', 'z'].entries()) {
        min[i] = Math.min(min[i], box.min[axis])
        max[i] = Math.max(max[i], box.max[axis])
      }
    })
    return {min, max}
  })
}

describeMobileAndDesktop('index.step logo', () => {
  test('loads and shows the logo assembly, one selectable node per block', async ({page}) => {
    test.setTimeout(TEST_TIMEOUT_MS)

    await homepageSetup(page)
    await setIsReturningUser(page.context())

    await page.goto('/share/v/p/index.step')
    await waitForModelReady(page)

    await page.getByTestId('control-button-navigation').click()
    await expect(page.getByTestId('NavTreePanel')).toBeVisible()

    const node = (label: string) => page.locator(`[data-node-label="${label}"]`)

    // The spatial chain the IFC tells as project/site/building/storey,
    // told here as nested assemblies. Each level has exactly one child,
    // so expanding straight down reaches the blocks.
    for (const name of ['Bldrs', 'Build', 'Every', 'Thing']) {
      await expect(node(name)).toHaveCount(1)
      await node(name).getByTestId('NavTreeNodeToggle').click()
    }

    // Seven occurrences, not two part types: STEP reuse is resolved per
    // occurrence, so every block gets its own row.
    await expect(node(NAME_LEAF)).toHaveCount(BLOCK_COUNT)

    // Selecting one block selects exactly that block — the four short
    // blocks share a part shape, and a type-keyed selection would light
    // up all of them.
    await node(NAME_LEAF).first().getByTestId('NavTreeNodeLabel').click()
    await expect(node(NAME_LEAF).first()).toHaveAttribute('data-is-selected', 'true')
    await expect(page.locator('[data-is-selected="true"]')).toHaveCount(1)
  })

  test('lands in the same world space as index.ifc, so one camera frames both', async ({page}) => {
    test.setTimeout(TEST_TIMEOUT_MS)

    await homepageSetup(page)
    await setIsReturningUser(page.context())

    // Why this needs pinning: Conway's `COORDINATE_TO_ORIGIN` open puts a
    // model's world origin at the FIRST geometry it emits — one
    // coordination matrix derived from that placement × the geometry's
    // first vertex, reused model-wide
    // (`compat/web-ifc/coordination_f64.deriveCoordinationF64`). So world
    // position depends on which element a file declares first, and the two
    // logo files only coincide because `makeIndexStep.mjs` lists its blocks
    // in the IFC's declaration order. Sorting that array by x — the obvious
    // tidy-up — slides the STEP model 76m down +X, which auto-framing hides
    // and only a `#c:` permalink reveals. That was the bug this test exists
    // to catch.
    await page.goto('/share/v/p/index.ifc')
    await waitForModelReady(page)
    const ifcBounds = await sceneBounds(page)

    await page.goto('/share/v/p/index.step')
    await waitForModelReady(page)
    const stepBounds = await sceneBounds(page)

    for (const corner of ['min', 'max'] as const) {
      for (const [axis, name] of ['x', 'y', 'z'].entries()) {
        const drift = Math.abs(stepBounds[corner][axis] - ifcBounds[corner][axis])
        expect(
          drift,
          `${corner}.${name} drifted: STEP ${stepBounds[corner][axis]} vs IFC ${ifcBounds[corner][axis]}`,
        ).toBeLessThan(ALIGNMENT_TOLERANCE_M)
      }
    }
  })
})
