import {expect, test} from '@playwright/test'
import {describeMobileAndDesktop} from '../tests/e2e/formFactor'
import {waitForModelReady} from '../tests/e2e/models'
import {homepageSetup, setIsReturningUser} from '../tests/e2e/utils'


/**
 * `/share/v/p/index.step` — the hosted STEP twin of the `index.ifc` logo,
 * generated by `tools/models/makeIndexStep.mjs` (see its README). It is
 * the default "open it in the viewer" target for the `/viewer/step` SEO
 * landing page, so it has to load through the STEP path and read as the
 * logo, not just parse.
 *
 * What this pins:
 *   - The file loads through Conway's AP214 path (a malformed BREP or a
 *     styling chain Conway doesn't walk still "loads" — it renders as
 *     nothing, or as default grey).
 *   - The assembly reads as the logo's sentence in the NavTree:
 *     Bldrs → Build → Every → Thing → Together ×7.
 *   - The seven blocks are seven independently selectable occurrences of
 *     two shared part shapes — the property that makes this a cheap
 *     regression asset for design/new/step-occurrence-selection.md.
 */
const NAME_LEAF = 'Together'
const BLOCK_COUNT = 7
// STEP parse + BREP tessellation is slower than an IFC smoke model, and
// the first load also warms the Conway wasm.
const TEST_TIMEOUT_MS = 60_000

describeMobileAndDesktop('index.step logo', () => {
  test('loads and shows the logo assembly, one selectable node per block', async ({page}) => {
    test.setTimeout(TEST_TIMEOUT_MS)

    await homepageSetup(page)
    await setIsReturningUser(page.context())

    await page.goto('/share/v/p/index.step')
    await waitForModelReady(page)

    await page.getByTestId('control-button-navigation').click()
    await expect(page.getByTestId('NavTreePanel')).toBeVisible()

    const node = (label: string) => page.locator(`[data-node-label="${label}"]`)

    // The spatial chain the IFC tells as project/site/building/storey,
    // told here as nested assemblies. Each level has exactly one child,
    // so expanding straight down reaches the blocks.
    for (const name of ['Bldrs', 'Build', 'Every', 'Thing']) {
      await expect(node(name)).toHaveCount(1)
      await node(name).getByTestId('NavTreeNodeToggle').click()
    }

    // Seven occurrences, not two part types: STEP reuse is resolved per
    // occurrence, so every block gets its own row.
    await expect(node(NAME_LEAF)).toHaveCount(BLOCK_COUNT)

    // Selecting one block selects exactly that block — the four short
    // blocks share a part shape, and a type-keyed selection would light
    // up all of them.
    await node(NAME_LEAF).first().getByTestId('NavTreeNodeLabel').click()
    await expect(node(NAME_LEAF).first()).toHaveAttribute('data-is-selected', 'true')
    await expect(page.locator('[data-is-selected="true"]')).toHaveCount(1)
  })
})
