/* eslint-disable no-magic-numbers */
import {LoadLogAccumulator, formatPreviewLine} from '@bldrs-ai/conway/src/core/progress_log'
import {parsePreviewLine, parseReportLines} from './loadReport'


/**
 * Contract test, not a string test.
 *
 * The point of these cases is that the *fixtures are generated by conway's
 * own formatter* (the same deep import loader/loadProgress.js uses), so the
 * day conway changes a report line the parser is told here rather than
 * silently returning nulls into a measurement record. That is the only way
 * to cover the `Preview:` line at all right now: no load this repo can run
 * emits one, because Share does not call `setPreviewStats` yet (conway
 * #544). See src/tests/e2e/loadReport.ts.
 */
describe('load report parsing', () => {
  describe('parsePreviewLine', () => {
    it('round-trips the line conway formats for a delivering channel', () => {
      const line = formatPreviewLine({
        firstMeshMs: 275,
        meshes: 1750,
        emitted: 539,
        deferred: 12,
        deferredOnPlacement: 11,
        retried: 8,
      })
      expect(parsePreviewLine(line)).toEqual({
        line,
        firstMeshMs: 275,
        meshes: 1750,
        units: 539,
        deferred: 12,
        deferredOnPlacement: 11,
        retried: 8,
      })
    })

    it('reads a channel that emitted nothing as a null first mesh', () => {
      // The blank-first-load case conway#543 exists to make attributable:
      // firstMeshMs is genuinely absent, and must not read as 0 ms.
      const line = formatPreviewLine({
        firstMeshMs: undefined,
        meshes: 0,
        emitted: 20,
        deferred: 20,
        deferredOnPlacement: 19,
        retried: 3,
      })
      const parsed = parsePreviewLine(line)
      expect(parsed?.firstMeshMs).toBeNull()
      expect(parsed?.deferred).toBe(20)
      expect(parsed?.deferredOnPlacement).toBe(19)
    })

    it('returns null for a line that is not a preview line', () => {
      expect(parsePreviewLine('Total: 1.402s')).toBeNull()
    })
  })

  describe('parseReportLines', () => {
    it('picks up stages and Total from lines conway formats', () => {
      const log = new LoadLogAccumulator()
      log.onProgress({phase: 'download', completed: 1, total: 1, elapsedMs: 0, memoryMb: 50})
      log.onProgress({phase: 'dataParse', completed: 1, total: 1, elapsedMs: 100, memoryMb: 60})
      log.onProgress({phase: 'geometry', completed: 1, total: 1, elapsedMs: 400, memoryMb: 90})
      log.closeCurrentStage(900, 120)
      const parsed = parseReportLines(log.allLines())
      expect(parsed.stages.map((s) => s.label)).toEqual(['Download', 'Parsing', 'Geometry'])
      expect(parsed.stages[1].seconds).toBeCloseTo(0.3, 3)
      expect(parsed.stages[1].heapDeltaMb).toBeCloseTo(30, 3)
      expect(parsed.total?.seconds).toBeCloseTo(0.9, 3)
      expect(parsed.total?.heapStartMb).toBeCloseTo(50, 3)
      expect(parsed.total?.heapEndMb).toBeCloseTo(120, 3)
    })

    it('leaves preview null when the report carries no Preview line', () => {
      // Today's state for every browser load, and the reason the field is
      // nullable rather than absent: a run must record "not reported"
      // distinctly from "reported as zero".
      const log = new LoadLogAccumulator()
      log.onProgress({phase: 'dataParse', completed: 1, total: 1, elapsedMs: 0})
      log.closeCurrentStage(500)
      const parsed = parseReportLines(log.allLines())
      expect(parsed).toHaveProperty('preview')
      expect(parsed.preview).toBeNull()
    })

    it('picks the Preview line up the moment the report grows one', () => {
      const log = new LoadLogAccumulator()
      log.onProgress({phase: 'dataParse', completed: 1, total: 1, elapsedMs: 0})
      log.setPreviewStats({
        firstMeshMs: 1234.5,
        meshes: 10,
        emitted: 4,
        deferred: 1,
        deferredOnPlacement: 1,
        retried: 0,
      })
      log.closeCurrentStage(2000)
      const parsed = parseReportLines(log.allLines())
      // conway renders seconds with three decimals, so the line carries
      // whole milliseconds and nothing finer. Worth knowing before
      // comparing a browser `Preview:` figure against the sub-ms numbers
      // scripts/preview_timeline.mjs prints: agreement below ~1 ms is not
      // observable through the report at all.
      expect(parsed.preview?.firstMeshMs).toBeCloseTo(1234.5, -1)
      expect(Math.abs((parsed.preview?.firstMeshMs ?? 0) - 1234.5)).toBeLessThanOrEqual(1)
      expect(parsed.preview?.meshes).toBe(10)
    })

    it('ignores preamble lines it does not recognize', () => {
      const parsed = parseReportLines([
        'Share 1.0.0',
        'Conway v1.588.1550',
        'Model: IFC4, 12 products',
        'Parsing: 1.500s',
        'Total: 2.000s',
      ])
      expect(parsed.modelLine).toBe('Model: IFC4, 12 products')
      expect(parsed.stages).toHaveLength(1)
      expect(parsed.stages[0].label).toBe('Parsing')
    })

    it('does not count a stage frozen mid-progress as a finished stage', () => {
      // A determinate stage that never reached 100% keeps its bar; that is
      // an aborted measurement, not a duration to average into a summary.
      const parsed = parseReportLines(['Geometry [0%.......57%] 9.100s', 'Total: 9.500s'])
      expect(parsed.stages).toHaveLength(0)
      expect(parsed.total?.seconds).toBeCloseTo(9.5, 3)
    })
  })
})
