/**
 * Renders floor plan elements as SVG.
 *
 * Architectural style: white background, thin black lines, proper dimension lines.
 */


// Architectural floor plan styling — clean thin lines on white
const STYLES = {
  wall: {fill: '#000', stroke: '#000', strokeWidth: 0.01, opacity: 1},
  column: {fill: '#000', stroke: '#000', strokeWidth: 0.01, opacity: 0.8},
  slab: {fill: 'none', stroke: '#999', strokeWidth: 0.01, opacity: 0.4},
  space: {fill: '#f0f4f8', stroke: '#ccc', strokeWidth: 0.005, opacity: 0.3},
  opening: {fill: '#fff', stroke: '#999', strokeWidth: 0.01, opacity: 1},
}

// Dimension line styling
const DIM = {
  stroke: '#666',
  strokeWidth: 0.012,
  fontSize: 0.16,
  textFill: '#444',
  extensionOvershoot: 0.06,
  offset: 0.35,
  tickSize: 0.06,
}


/**
 * Generate an SVG string from floor plan elements.
 */
export function renderSVG(elements, measurements = [], annotations = [], options = {}) {
  const {scale = 100, padding = 2, title = '', storey = ''} = options

  const bounds = computeBounds(elements, padding)
  if (!bounds) return '<svg xmlns="http://www.w3.org/2000/svg"></svg>'

  const width = bounds.maxX - bounds.minX
  const height = bounds.maxZ - bounds.minZ

  const svgWidthMM = (width / scale) * 1000
  const svgHeightMM = (height / scale) * 1000

  const lines = []
  lines.push(`<svg xmlns="http://www.w3.org/2000/svg"`)
  lines.push(`  viewBox="${bounds.minX} ${bounds.minZ} ${width} ${height}"`)
  lines.push(`  width="${svgWidthMM.toFixed(0)}mm" height="${svgHeightMM.toFixed(0)}mm"`)
  lines.push(`  style="background: #ffffff">`)

  lines.push(`  <!-- Generated by Bldrs Share - ${new Date().toISOString()} -->`)
  if (title) lines.push(`  <!-- Model: ${escXml(title)} -->`)
  if (storey) lines.push(`  <!-- Storey: ${escXml(storey)} -->`)
  lines.push(`  <!-- Scale: 1:${scale} -->`)

  // Render layers
  const layerOrder = ['slab', 'space', 'wall', 'column', 'opening']
  for (const category of layerOrder) {
    const layerEls = elements.filter((e) => e.category === category)
    if (layerEls.length === 0) continue

    lines.push(`  <g class="layer-${category}s" data-layer="${category}">`)
    for (const el of layerEls) {
      const style = STYLES[el.category] || STYLES.wall
      const pts = el.polygon.map(([x, z]) => `${x.toFixed(4)},${z.toFixed(4)}`).join(' ')
      const nameAttr = el.name ? ` data-name="${escXml(el.name)}"` : ''
      lines.push(`    <polygon points="${pts}" fill="${style.fill}" stroke="${style.stroke}" stroke-width="${style.strokeWidth}" opacity="${style.opacity}" data-express-id="${el.expressId}" data-type="${el.type}"${nameAttr}/>`)

      if (el.category === 'space' && el.name) {
        const c = centroid(el.polygon)
        lines.push(`    <text x="${c[0].toFixed(4)}" y="${c[1].toFixed(4)}" font-family="Helvetica, Arial, sans-serif" font-size="0.20" fill="#555" text-anchor="middle" dominant-baseline="middle" font-weight="300">${escXml(el.name)}</text>`)
      }
    }
    lines.push(`  </g>`)
  }

  // User measurements: distance lines + area polygons
  const distMeasurements = measurements.filter((m) => m.type === 'distance')
  const areaMeasurements = measurements.filter((m) => m.type === 'area')

  if (areaMeasurements.length > 0) {
    lines.push(`  <g class="layer-areas" data-layer="areas">`)
    for (const a of areaMeasurements) {
      lines.push(renderAreaMeasurement(a))
    }
    lines.push(`  </g>`)
  }

  if (distMeasurements.length > 0) {
    lines.push(`  <g class="layer-dimensions" data-layer="dimensions">`)
    for (const m of distMeasurements) {
      lines.push(renderDimLine(m))
    }
    lines.push(`  </g>`)
  }

  // Annotations
  if (annotations.length > 0) {
    lines.push(`  <g class="layer-annotations" data-layer="annotations">`)
    for (const a of annotations) {
      lines.push(`    <text x="${a.x.toFixed(4)}" y="${a.z.toFixed(4)}" font-family="Helvetica, Arial, sans-serif" font-size="0.16" fill="#333">${escXml(a.text)}</text>`)
    }
    lines.push(`  </g>`)
  }

  // Scale bar + title block
  lines.push(scaleBar(bounds, scale))
  if (storey) lines.push(titleBlock(bounds, storey, scale))

  lines.push(`</svg>`)
  return lines.join('\n')
}


/**
 * Auto-generate dimension lines along the longest edge of each wall.
 */
function generateAutoDimensions(elements) {
  const dims = []
  const walls = elements.filter((e) => e.category === 'wall')

  for (const wall of walls) {
    const p = wall.polygon
    if (p.length < 2) continue

    let maxLen = 0
    let best = null
    for (let i = 0; i < p.length; i++) {
      const j = (i + 1) % p.length
      const len = dist(p[i], p[j])
      if (len > maxLen) { maxLen = len; best = [p[i], p[j]] }
    }

    if (best && maxLen > 0.5) {
      dims.push({id: `auto-${wall.expressId}`, type: 'distance', from: best[0], to: best[1], distance: maxLen, auto: true})
    }
  }
  return dims
}


/**
 * Render a completed area measurement: filled polygon + area label at centroid.
 */
function renderAreaMeasurement(a) {
  const pts = a.points.map(([x, z]) => `${x.toFixed(4)},${z.toFixed(4)}`).join(' ')
  const c = centroid(a.points)
  const label = a.area >= 1 ? `${a.area.toFixed(1)} m²` : `${(a.area * 10000).toFixed(0)} cm²`

  return [
    `    <polygon points="${pts}" fill="rgba(0,150,200,0.12)" stroke="#0096c8" stroke-width="0.02"/>`,
    `    <text x="${c[0].toFixed(4)}" y="${c[1].toFixed(4)}" font-family="Helvetica, Arial, sans-serif" font-size="0.25" fill="#0096c8" text-anchor="middle" dominant-baseline="middle" font-weight="500">${label}</text>`,
  ].join('\n')
}


/**
 * Render a proper architectural dimension line:
 * extension lines + dimension line + tick marks + text.
 */
function renderDimLine(m) {
  const [x1, z1] = m.from
  const [x2, z2] = m.to
  const d = m.distance

  const dx = x2 - x1
  const dz = z2 - z1
  const len = Math.sqrt(dx * dx + dz * dz)
  if (len < 0.01) return ''

  // Perpendicular unit normal
  const nx = -dz / len
  const nz = dx / len

  const off = DIM.offset
  const ov = DIM.extensionOvershoot
  const tk = DIM.tickSize
  const sw = DIM.strokeWidth
  const col = m.auto ? DIM.stroke : '#c00'
  const tcol = m.auto ? DIM.textFill : '#c00'

  // Offset points (dimension line position)
  const ox1 = x1 + nx * off, oz1 = z1 + nz * off
  const ox2 = x2 + nx * off, oz2 = z2 + nz * off
  const mx = (ox1 + ox2) / 2, mz = (oz1 + oz2) / 2

  const angle = Math.atan2(dz, dx) * 180 / Math.PI

  // Format label
  const label = d >= 1 ? d.toFixed(2) : `${(d * 100).toFixed(0)}cm`

  const f = (v) => v.toFixed(4)

  return [
    // Extension lines
    `    <line x1="${f(x1)}" y1="${f(z1)}" x2="${f(ox1 + nx * ov)}" y2="${f(oz1 + nz * ov)}" stroke="${col}" stroke-width="${sw}"/>`,
    `    <line x1="${f(x2)}" y1="${f(z2)}" x2="${f(ox2 + nx * ov)}" y2="${f(oz2 + nz * ov)}" stroke="${col}" stroke-width="${sw}"/>`,
    // Dimension line
    `    <line x1="${f(ox1)}" y1="${f(oz1)}" x2="${f(ox2)}" y2="${f(oz2)}" stroke="${col}" stroke-width="${sw}"/>`,
    // Tick marks (diagonal slashes at each end)
    `    <line x1="${f(ox1 - dx / len * tk + nx * tk)}" y1="${f(oz1 - dz / len * tk + nz * tk)}" x2="${f(ox1 + dx / len * tk - nx * tk)}" y2="${f(oz1 + dz / len * tk - nz * tk)}" stroke="${col}" stroke-width="${sw * 1.5}"/>`,
    `    <line x1="${f(ox2 - dx / len * tk - nx * tk)}" y1="${f(oz2 - dz / len * tk - nz * tk)}" x2="${f(ox2 + dx / len * tk + nx * tk)}" y2="${f(oz2 + dz / len * tk + nz * tk)}" stroke="${col}" stroke-width="${sw * 1.5}"/>`,
    // Text
    `    <text x="${f(mx)}" y="${f(mz)}" font-family="Helvetica, Arial, sans-serif" font-size="${DIM.fontSize}" fill="${tcol}" text-anchor="middle" dominant-baseline="middle" transform="rotate(${angle.toFixed(1)}, ${f(mx)}, ${f(mz)})">${label}</text>`,
  ].join('\n')
}


function scaleBar(bounds, scale) {
  const len = scale >= 200 ? 5 : scale >= 100 ? 2 : 1
  const x = bounds.minX + 0.5
  const z = bounds.maxZ - 0.5
  return [
    `  <g class="scale-bar">`,
    `    <line x1="${x}" y1="${z}" x2="${x + len}" y2="${z}" stroke="#000" stroke-width="0.025"/>`,
    `    <line x1="${x}" y1="${z - 0.1}" x2="${x}" y2="${z + 0.1}" stroke="#000" stroke-width="0.025"/>`,
    `    <line x1="${x + len}" y1="${z - 0.1}" x2="${x + len}" y2="${z + 0.1}" stroke="#000" stroke-width="0.025"/>`,
    `    <text x="${x + len / 2}" y="${z - 0.18}" font-family="Helvetica, Arial, sans-serif" font-size="0.14" fill="#000" text-anchor="middle">${len}m</text>`,
    `    <text x="${x + len / 2}" y="${z + 0.28}" font-family="Helvetica, Arial, sans-serif" font-size="0.10" fill="#888" text-anchor="middle">1:${scale}</text>`,
    `  </g>`,
  ].join('\n')
}


function titleBlock(bounds, storey, scale) {
  const x = bounds.maxX - 0.3
  const z = bounds.maxZ - 0.3
  return [
    `  <g class="title-block">`,
    `    <text x="${x}" y="${z - 0.2}" font-family="Helvetica, Arial, sans-serif" font-size="0.20" fill="#000" text-anchor="end" font-weight="500">${escXml(storey)}</text>`,
    `    <text x="${x}" y="${z}" font-family="Helvetica, Arial, sans-serif" font-size="0.11" fill="#888" text-anchor="end">Scale 1:${scale}</text>`,
    `  </g>`,
  ].join('\n')
}


function computeBounds(elements, padding) {
  if (elements.length === 0) return null
  let minX = Infinity, maxX = -Infinity, minZ = Infinity, maxZ = -Infinity
  for (const el of elements) {
    for (const [x, z] of el.polygon) {
      if (x < minX) minX = x
      if (x > maxX) maxX = x
      if (z < minZ) minZ = z
      if (z > maxZ) maxZ = z
    }
  }
  return {minX: minX - padding, maxX: maxX + padding, minZ: minZ - padding, maxZ: maxZ + padding}
}


function centroid(polygon) {
  let cx = 0, cz = 0
  for (const [x, z] of polygon) { cx += x; cz += z }
  return [cx / polygon.length, cz / polygon.length]
}


function dist(a, b) {
  return Math.sqrt((b[0] - a[0]) ** 2 + (b[1] - a[1]) ** 2)
}


function escXml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
