/**
 * Renders floor plan elements as SVG.
 *
 * Converts world-coordinate polygons to SVG coordinates,
 * applies architectural styling per category.
 */


const STYLES = {
  wall: {fill: '#666', stroke: '#333', strokeWidth: 0.5, opacity: 1},
  column: {fill: '#888', stroke: '#444', strokeWidth: 0.3, opacity: 1},
  space: {fill: '#4fc3f7', stroke: 'none', strokeWidth: 0, opacity: 0.08},
  slab: {fill: 'none', stroke: '#999', strokeWidth: 0.3, opacity: 0.5},
  opening: {fill: '#1A1A1A', stroke: '#999', strokeWidth: 0.2, opacity: 0.8},
}


/**
 * Generate an SVG string from floor plan elements.
 *
 * @param {Array<FloorPlanElement>} elements
 * @param {Array<Measurement>} measurements
 * @param {Array<Annotation>} annotations
 * @param {object} options
 * @param {number} options.scale - e.g., 100 for 1:100
 * @param {number} options.padding - padding in meters
 * @param {string} options.title
 * @param {string} options.storey
 * @return {string} SVG markup
 */
export function renderSVG(elements, measurements = [], annotations = [], options = {}) {
  const {scale = 100, padding = 1, title = '', storey = ''} = options

  // Compute bounding box of all elements
  const bounds = computeBounds(elements, padding)
  if (!bounds) return '<svg xmlns="http://www.w3.org/2000/svg"></svg>'

  const width = bounds.maxX - bounds.minX
  const height = bounds.maxZ - bounds.minZ

  // SVG dimensions in mm at given scale (1:100 → 1m = 10mm on paper)
  const svgWidthMM = (width / scale) * 1000
  const svgHeightMM = (height / scale) * 1000

  const lines = []
  lines.push(`<svg xmlns="http://www.w3.org/2000/svg"`)
  lines.push(`  viewBox="${bounds.minX} ${bounds.minZ} ${width} ${height}"`)
  lines.push(`  width="${svgWidthMM.toFixed(0)}mm" height="${svgHeightMM.toFixed(0)}mm"`)
  lines.push(`  style="background: #1A1A1A">`)

  // Metadata
  lines.push(`  <!-- Generated by Bldrs Share - ${new Date().toISOString()} -->`)
  if (title) lines.push(`  <!-- Model: ${escXml(title)} -->`)
  if (storey) lines.push(`  <!-- Storey: ${escXml(storey)} -->`)
  lines.push(`  <!-- Scale: 1:${scale} -->`)

  // Render layers in order: slabs → spaces → walls → columns → openings
  const layerOrder = ['slab', 'space', 'wall', 'column', 'opening']
  for (const category of layerOrder) {
    const layerElements = elements.filter((e) => e.category === category)
    if (layerElements.length === 0) continue

    lines.push(`  <g class="layer-${category}s" data-layer="${category}">`)
    for (const el of layerElements) {
      const style = STYLES[el.category] || STYLES.wall
      const points = el.polygon.map(([x, z]) => `${x.toFixed(4)},${z.toFixed(4)}`).join(' ')
      const label = el.name ? ` data-name="${escXml(el.name)}"` : ''
      lines.push(`    <polygon points="${points}"`)
      lines.push(`      fill="${style.fill}" stroke="${style.stroke}"`)
      lines.push(`      stroke-width="${style.strokeWidth}" opacity="${style.opacity}"`)
      lines.push(`      data-express-id="${el.expressId}" data-type="${el.type}"${label}/>`)

      // Add space labels
      if (el.category === 'space' && el.name) {
        const centroid = computeCentroid(el.polygon)
        lines.push(`    <text x="${centroid[0].toFixed(4)}" y="${centroid[1].toFixed(4)}"`)
        lines.push(`      font-family="sans-serif" font-size="${0.3}" fill="#999"`)
        lines.push(`      text-anchor="middle" dominant-baseline="middle">${escXml(el.name)}</text>`)
      }
    }
    lines.push(`  </g>`)
  }

  // Measurements layer
  if (measurements.length > 0) {
    lines.push(`  <g class="layer-dimensions" data-layer="dimensions">`)
    for (const m of measurements) {
      lines.push(renderMeasurement(m))
    }
    lines.push(`  </g>`)
  }

  // Annotations layer
  if (annotations.length > 0) {
    lines.push(`  <g class="layer-annotations" data-layer="annotations">`)
    for (const a of annotations) {
      lines.push(renderAnnotation(a))
    }
    lines.push(`  </g>`)
  }

  // Scale bar
  lines.push(renderScaleBar(bounds, scale))

  lines.push(`</svg>`)
  return lines.join('\n')
}


/**
 * Render a measurement as SVG dimension line.
 *
 * @param {Measurement} m
 * @return {string}
 */
function renderMeasurement(m) {
  const [x1, z1] = m.from
  const [x2, z2] = m.to
  const dist = m.distance
  const mx = (x1 + x2) / 2
  const mz = (z1 + z2) / 2

  // Offset for dimension text
  const dx = x2 - x1
  const dz = z2 - z1
  const len = Math.sqrt(dx * dx + dz * dz)
  const nx = len > 0 ? -dz / len * 0.3 : 0
  const nz = len > 0 ? dx / len * 0.3 : 0.3

  return [
    `    <line x1="${x1.toFixed(4)}" y1="${z1.toFixed(4)}"`,
    `      x2="${x2.toFixed(4)}" y2="${z2.toFixed(4)}"`,
    `      stroke="#FF6B35" stroke-width="0.05" stroke-dasharray="0.1,0.05"/>`,
    `    <circle cx="${x1.toFixed(4)}" cy="${z1.toFixed(4)}" r="0.08" fill="#FF6B35"/>`,
    `    <circle cx="${x2.toFixed(4)}" cy="${z2.toFixed(4)}" r="0.08" fill="#FF6B35"/>`,
    `    <text x="${(mx + nx).toFixed(4)}" y="${(mz + nz).toFixed(4)}"`,
    `      font-family="sans-serif" font-size="0.25" fill="#FF6B35"`,
    `      text-anchor="middle" dominant-baseline="middle">${dist.toFixed(2)}m</text>`,
  ].join('\n')
}


function renderAnnotation(a) {
  return [
    `    <text x="${a.x.toFixed(4)}" y="${a.z.toFixed(4)}"`,
    `      font-family="sans-serif" font-size="0.2" fill="#00D4AA"`,
    `      text-anchor="start">${escXml(a.text)}</text>`,
  ].join('\n')
}


function renderScaleBar(bounds, scale) {
  const barLength = scale >= 200 ? 5 : scale >= 100 ? 2 : 1
  const x = bounds.minX + 0.5
  const z = bounds.maxZ - 0.5

  return [
    `  <g class="scale-bar">`,
    `    <line x1="${x}" y1="${z}" x2="${x + barLength}" y2="${z}"`,
    `      stroke="#fff" stroke-width="0.05"/>`,
    `    <line x1="${x}" y1="${z - 0.15}" x2="${x}" y2="${z + 0.15}" stroke="#fff" stroke-width="0.05"/>`,
    `    <line x1="${x + barLength}" y1="${z - 0.15}" x2="${x + barLength}" y2="${z + 0.15}" stroke="#fff" stroke-width="0.05"/>`,
    `    <text x="${x + barLength / 2}" y="${z - 0.25}"`,
    `      font-family="sans-serif" font-size="0.2" fill="#fff"`,
    `      text-anchor="middle">${barLength}m (1:${scale})</text>`,
    `  </g>`,
  ].join('\n')
}


function computeBounds(elements, padding) {
  if (elements.length === 0) return null
  let minX = Infinity, maxX = -Infinity, minZ = Infinity, maxZ = -Infinity
  for (const el of elements) {
    for (const [x, z] of el.polygon) {
      if (x < minX) minX = x
      if (x > maxX) maxX = x
      if (z < minZ) minZ = z
      if (z > maxZ) maxZ = z
    }
  }
  return {
    minX: minX - padding,
    maxX: maxX + padding,
    minZ: minZ - padding,
    maxZ: maxZ + padding,
  }
}


function computeCentroid(polygon) {
  let cx = 0, cz = 0
  for (const [x, z] of polygon) {
    cx += x
    cz += z
  }
  return [cx / polygon.length, cz / polygon.length]
}


function escXml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
