const GITHUB_BASE_URL = process.env.GITHUB_BASE_URL


export const MOCK_COMMENTS = {
  data: [
    {
      url: `${GITHUB_BASE_URL}/repos/pablo-mayrgundter/Share/issues/comments/1144935479`,
      html_url: 'https://github.com/pablo-mayrgundter/Share/issues/17#issuecomment-1144935479',
      issue_url: `${GITHUB_BASE_URL}/repos/pablo-mayrgundter/Share/issues/17`,
      id: 1144935480,
      node_id: 'IC_kwDOFwgxOc5EPlQ3',
      number: 1,
      user: {
        login: 'OlegMoshkovich',
        id: 3433607,
        node_id: 'MDQ6VXNlcjM0MzM2MDY=',
        avatar_url: 'src/assets/avatarMock.png',
        gravatar_id: '',
        url: `${GITHUB_BASE_URL}/users/OlegMoshkovich`,
        html_url: 'https://github.com/OlegMoshkovich',
        followers_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/followers`,
        following_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/following{/other_user}`,
        gists_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/gists{/gist_id}`,
        starred_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/starred{/owner}{/repo}`,
        subscriptions_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/subscriptions`,
        organizations_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/orgs`,
        repos_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/repos`,
        events_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/events{/privacy}`,
        received_events_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/received_events`,
        type: 'User',
        site_admin: false,
      },
      created_at: '2022-06-02T14:31:04Z',
      updated_at: '2022-06-08T08:18:43Z',
      author_association: 'NONE',
      body: `testComment_1`,
      reactions: {
        'url': `${GITHUB_BASE_URL}/repos/pablo-mayrgundter/Share/issues/comments/1144935479/reactions`,
        'total_count': 0,
        '+1': 0,
        '-1': 0,
        'laugh': 0,
        'hooray': 0,
        'confused': 0,
        'heart': 0,
        'rocket': 0,
        'eyes': 0,
      },
      performed_via_github_app: null,
    },
    {
      url: `${GITHUB_BASE_URL}/repos/pablo-mayrgundter/Share/issues/comments/1144935479`,
      html_url: 'https://github.com/pablo-mayrgundter/Share/issues/17#issuecomment-1144935479',
      issue_url: `${GITHUB_BASE_URL}/repos/pablo-mayrgundter/Share/issues/17`,
      id: 1144935481,
      number: 2,
      node_id: 'IC_kwDOFwgxOc5EPlQ3',
      user: {
        login: 'OlegMoshkovich',
        id: 3433606,
        node_id: 'MDQ6VXNlcjM0MzM2MDY=',
        avatar_url: 'src/assets/avatarMock.png',
        gravatar_id: '',
        url: `${GITHUB_BASE_URL}/users/OlegMoshkovich`,
        html_url: 'https://github.com/OlegMoshkovich',
        followers_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/followers`,
        following_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/following{/other_user}`,
        gists_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/gists{/gist_id}`,
        starred_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/starred{/owner}{/repo}`,
        subscriptions_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/subscriptions`,
        organizations_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/orgs`,
        repos_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/repos`,
        events_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/events{/privacy}`,
        received_events_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/received_events`,
        type: 'User',
        site_admin: false,
      },
      created_at: '2022-06-02T14:31:04Z',
      updated_at: '2022-06-08T08:18:43Z',
      author_association: 'NONE',
      body: `testComment_2`,
      reactions: {
        'url': `${GITHUB_BASE_URL}/repos/pablo-mayrgundter/Share/issues/comments/1144935479/reactions`,
        'total_count': 0,
        '+1': 0,
        '-1': 0,
        'laugh': 0,
        'hooray': 0,
        'confused': 0,
        'heart': 0,
        'rocket': 0,
        'eyes': 0,
      },
      performed_via_github_app: null,
    },
  ],
}

export const MOCK_COMMENT = {
      url: `${GITHUB_BASE_URL}/repos/pablo-mayrgundter/Share/issues/comments/1144935479`,
      html_url: 'https://github.com/pablo-mayrgundter/Share/issues/17#issuecomment-1144935479',
      issue_url: `${GITHUB_BASE_URL}/repos/pablo-mayrgundter/Share/issues/17`,
      id: 1144935480,
      node_id: 'IC_kwDOFwgxOc5EPlQ3',
      number: 1,
      user: {
        login: 'cypresstester',
        id: 3433607,
        node_id: 'MDQ6VXNlcjM0MzM2MDY=',
        avatar_url: 'src/assets/avatarMock.png',
        gravatar_id: '',
        url: `${GITHUB_BASE_URL}/users/OlegMoshkovich`,
        html_url: 'https://github.com/OlegMoshkovich',
        followers_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/followers`,
        following_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/following{/other_user}`,
        gists_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/gists{/gist_id}`,
        starred_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/starred{/owner}{/repo}`,
        subscriptions_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/subscriptions`,
        organizations_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/orgs`,
        repos_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/repos`,
        events_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/events{/privacy}`,
        received_events_url: `${GITHUB_BASE_URL}/users/OlegMoshkovich/received_events`,
        type: 'User',
        site_admin: false,
      },
      created_at: '2022-06-02T14:31:04Z',
      updated_at: '2022-06-08T08:18:43Z',
      author_association: 'NONE',
      body: `created_comment_body`,
      reactions: {
        'url': `${GITHUB_BASE_URL}/repos/pablo-mayrgundter/Share/issues/comments/1144935479/reactions`,
        'total_count': 0,
        '+1': 0,
        '-1': 0,
        'laugh': 0,
        'hooray': 0,
        'confused': 0,
        'heart': 0,
        'rocket': 0,
        'eyes': 0,
      },
      performed_via_github_app: null,
    }
