name: Reusable Cypress

on:
  workflow_call:
    inputs:
      runner:
        description: Runner label to use
        required: true
        type: string
      timeout_minutes:
        description: Timeout (minutes)
        required: false
        type: number
        default: 20
      browser:
        description: Cypress browser
        required: false
        type: string
        default: chrome
      command:
        description: Cypress command
        required: false
        type: string
        default: yarn cy-parallel

permissions:
  contents: read

jobs:
  cypress-run:
    name: run on ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout_minutes }}

    concurrency:
      group: cypress-group
      cancel-in-progress: true

    environment: cypress

    steps:
      # ---- Claim ASAP so fallback can detect that this job actually started
      - name: Upload runner-start claim
        run: |
          echo "claimed:${{ inputs.runner }} $(date -u +%FT%TZ)" > claim.txt
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: runner-claim
          path: claim.txt
          retention-days: 1

      # ---- Your existing flow below ----
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cache Cypress binary + node_modules (your current config)
      - name: Cache Cypress and Node Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Clear Cypress Cache
        run: npx cypress cache prune

      - name: Install deps (frozen)
        run: yarn install --frozen-lockfile

      - name: Install Cypress Binary
        run: npx cypress install

      - name: Verify Cypress Installation
        run: npx cypress info

      - name: Build (docs/)
        run: yarn cy-build
        env:
          NODE_ENV: production
          SHARE_CONFIG: cypress

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ inputs.browser }}
          command: ${{ inputs.command }}
        env:
          # keep these exactly as in your current workflow
          GITHUB_BASE_URL: https://git.bldrs.dev.cy/p/gh
          GITHUB_BASE_URL_UNAUTHENTICATED: https://api.github.com.cy
          RAW_GIT_PROXY_URL_NEW: https://rawgit.bldrs.dev.cy/model
          RAW_GIT_PROXY_URL: https://rawgit.bldrs.dev.cy/r
          MSW_IS_ENABLED: true
